services:
  llarpd-router:
    image: ghcr.io/majestrate/llarp:latest
    environment:
      LLARP_DATA_DIR: "/data"
      LLARP_PUBLIC_IP: "public.ip.goes.here"
    volumes:
      - data:/data
    ports:
      - "1090:1090/udp"
volumes:
  data:
